//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManager.Resources.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopManager.Resources.Locale.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account management.
        /// </summary>
        public static string Account_management {
            get {
                return ResourceManager.GetString("Account management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category.
        /// </summary>
        public static string Add_a_new_category {
            get {
                return ResourceManager.GetString("Add a new category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user:.
        /// </summary>
        public static string Add_new_user_ {
            get {
                return ResourceManager.GetString("Add new user:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string Add_product {
            get {
                return ResourceManager.GetString("Add product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN: Manage users.
        /// </summary>
        public static string ADMIN__Manage_users {
            get {
                return ResourceManager.GetString("ADMIN: Manage users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password:.
        /// </summary>
        public static string Admin_password_ {
            get {
                return ResourceManager.GetString("Admin password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin username:.
        /// </summary>
        public static string Admin_username_ {
            get {
                return ResourceManager.GetString("Admin username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also update product stock (quantity).
        /// </summary>
        public static string Also_update_product_stock {
            get {
                return ResourceManager.GetString("Also update product stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any modification will be applied immediately!!!.
        /// </summary>
        public static string Any_modification_will_be_applied_immediately___ {
            get {
                return ResourceManager.GetString("Any modification will be applied immediately!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only update a single category simultaneously!.
        /// </summary>
        public static string Can_only_update_a_single_category_simultaneously_ {
            get {
                return ResourceManager.GetString("Can only update a single category simultaneously!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username.
        /// </summary>
        public static string Change_username {
            get {
                return ResourceManager.GetString("Change username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new sale.
        /// </summary>
        public static string Create_a_new_sale {
            get {
                return ResourceManager.GetString("Create a new sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sale.
        /// </summary>
        public static string Create_sale {
            get {
                return ResourceManager.GetString("Create sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Delete_selected {
            get {
                return ResourceManager.GetString("Delete selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all the changes made from the last save.
        /// </summary>
        public static string Discard_all_the_changes_made_from_the_last_save {
            get {
                return ResourceManager.GetString("Discard all the changes made from the last save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string Discard_changes {
            get {
                return ResourceManager.GetString("Discard changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string Expiry_date {
            get {
                return ResourceManager.GetString("Expiry date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to the shop manager.
        /// </summary>
        public static string Log_in_to_the_shop_manager {
            get {
                return ResourceManager.GetString("Log in to the shop manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string Manage_users {
            get {
                return ResourceManager.GetString("Manage users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify an existing sale.
        /// </summary>
        public static string Modify_an_existing_sale {
            get {
                return ResourceManager.GetString("Modify an existing sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify sale.
        /// </summary>
        public static string Modify_sale {
            get {
                return ResourceManager.GetString("Modify sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user data:.
        /// </summary>
        public static string Modify_user_data_ {
            get {
                return ResourceManager.GetString("Modify user data:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for the selected category.
        /// </summary>
        public static string New_name_for_the_selected_category {
            get {
                return ResourceManager.GetString("New name for the selected category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string New_password_ {
            get {
                return ResourceManager.GetString("New password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New username:.
        /// </summary>
        public static string New_username_ {
            get {
                return ResourceManager.GetString("New username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of products.
        /// </summary>
        public static string Number_of_products {
            get {
                return ResourceManager.GetString("Number of products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_ {
            get {
                return ResourceManager.GetString("Password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per KG.
        /// </summary>
        public static string Price_per_KG {
            get {
                return ResourceManager.GetString("Price per KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product categories.
        /// </summary>
        public static string Product_categories {
            get {
                return ResourceManager.GetString("Product categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        public static string Product_category {
            get {
                return ResourceManager.GetString("Product category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string Purchase_date {
            get {
                return ResourceManager.GetString("Purchase date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an account, ask the shop administrator
        ///to log in and add you to the application&apos;s database..
        /// </summary>
        public static string REGISTER_EXPLANATION {
            get {
                return ResourceManager.GetString("REGISTER_EXPLANATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date and time.
        /// </summary>
        public static string Select_date_and_time {
            get {
                return ResourceManager.GetString("Select date and time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop manager.
        /// </summary>
        public static string Shop_manager {
            get {
                return ResourceManager.GetString("Shop manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username_ {
            get {
                return ResourceManager.GetString("Username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
